// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EAudit.Models
{
    [Table("Org")]
    public partial class Org
    {
        [Column("MemID")]
        [StringLength(30)]
        [Key]
        public string MemId { get; set; }
        [Column("OrgName")]
        [StringLength(8)]
        public string OrgName { get; set; }
        [Column("DepID")]
        [StringLength(30)]
        public string DepId { get; set; }
        [Column("DEPNAME")]
        [StringLength(100)]
        public string Depname { get; set; }
        [Column("RolID")]
        [StringLength(30)]
        public string RolId { get; set; }
        [Column("ROLNAME")]
        [StringLength(250)]
        public string Rolname { get; set; }

        [Column("LoginID")]
        [StringLength(50)]
        public string LoginId { get; set; }
        [StringLength(100)]
        public string Password { get; set; }
        [StringLength(250)]
        public string UserName { get; set; }
    }
}